//auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

//videos
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";

//Select Video by ID
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL";
export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";

//Select Channel details by ChannelID
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";

//Select get Subscription status ChannelID
export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

//Comment List
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";
export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";

//Add comment
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

//Related videos List
export const RELATED_VIDEOS_SUCCESS = "RELATED_VIDEOS_SUCCESS";
export const RELATED_VIDEOS_FAIL = "RELATED_VIDEOS_FAIL";
export const RELATED_VIDEOS_REQUEST = "RELATED_VIDEOS_REQUEST";

//Search component List
export const SEARCHED_VIDEOS_SUCCESS = "SEARCHED_VIDEOS_SUCCESS";
export const SEARCHED_VIDEOS_FAIL = "SEARCHED_VIDEOS_FAIL";
export const SEARCHED_VIDEOS_REQUEST = "SEARCHED_VIDEOS_REQUEST";

//Subscription channel List
export const SUBSCRIPTION_CHANNEL_SUCCESS = "SUBSCRIPTION_CHANNEL_SUCCESS";
export const SUBSCRIPTION_CHANNEL_FAIL = "SUBSCRIPTION_CHANNEL_FAIL";
export const SUBSCRIPTION_CHANNEL_REQUEST = "SUBSCRIPTION_CHANNEL_REQUEST";

//Subscription channel List
export const CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_VIDEOS_FAIL = "CHANNEL_VIDEOS_FAIL";
export const CHANNEL_VIDEOS_REQUEST = "CHANNEL_VIDEOS_REQUEST";
